services:
  postgres:
    ports:
      - "5435:5432"

  redis:
    ports:
      - "6379:6379"

  langfuse:
    ports:
      - "3001:3000"

  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"


  # Dev Tools
  redisinsight:
    image: redis/redisinsight:latest
    profiles: ["dev"]
    ports:
      - "8001:8001"
    networks:
      - internal
      - public
